### ISSUE TITLE
[suggest] Some suggest for tool in my feeling

### ISSUE THREAD

**Issue by uptutu** [tkeel-io/tkeel-Interface#9]
1. We have a full layout specification and when using the tool to generate files such as `proto` and `service`, we could perhaps not specify a path.
2. Perhaps we could use the `hello` folder in `cmd/hello/main.go`.
3. I also have a question: why is the registration of the service in the program entry point of the `cmd` file? And not in the `server`.
4. The `pkg` looks more like a useless organizational folder. 
The `service` folder is very closely related to the stuff in `api`, but they are separated by a `pkg`.
5. The HTTP Router generated by the template is not a canonical RESTful design.
Attention should also be paid to the singular and plural of the generated modules. For example, if I want to generate a module called `model`, then the corresponding route should be
    - GET models/:id
    - GET models

#### refs: 
[Laravel artisan  generating-commands](https://laravel.com/docs/8.x/artisan#generating-commands)
[Laravel artisan command generate a model](https://laravel.com/docs/8.x/eloquent#generating-model-classes)
 [Microsoft RESTful Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md)
[Github RESTful](https://docs.github.com/en/rest/overview/resources-in-the-rest-api)

**Comment by imneov** [comment]
Q：1. We have a full layout specification and when using the tool to generate files such as proto and service, we could perhaps not specify a path.
----------------------------------------------------------------------------
A：How about specifying the output path through parameters

**Comment by uptutu** [comment]
> ## Q：1. We have a full layout specification and when using the tool to generate files such as proto and service, we could perhaps not specify a path.
> 
> A：How about specifying the output path through parameters

👍  This would be great.

Our current usage is as follows：
```
# Generate proto template
$ tkeel-tool proto add api/helloworld/v1/helloworld.proto
```

In my imagination， It's maybe like this:
```
# Just the exact name. 
# Then , That will gen specify proto file in `api/helloworld`

$ tkeel-tool make proto helloworld
```
becuz we offer this layout to developers, helped them sort out where some of the code should be placed.

Of course, we can also let the user customise where the code that generates it is located, just by providing him with a default value.
```
# gen api/somewhere/want/that/be/heeloworld.proto
$ tkeel-tool make proto helloworld api/somewhere/want/that/be

# or use flag
$ tkeel-tool make proto helloworld --dir api/somewhere/want/that/be
```
more like, Laravel command `artisan`. User experience may be better.

[Artisan 命令 ](https://learnku.com/articles/29120)

**Comment by imneov** [comment]
Very good suggestion!

1. I absolutely agree that the project should be arranged in accordance with the discussion of layout specifications, so as to ensure the consistency of our project and reduce communication costs. Our discussion is here [PKG Layout](https://docs.google.com/document/d/153ltyIkEYOV7klYo-JHekYhRMcnleu08ZZk5Jus5UZA/edit#heading=h.zgln0pngpjgc)

2. The main consideration here is the possibility of reuse. In fact, the only difference is the binary name when installed with `go get`

3. Refer to this question Question 2

4. Refer to this question Question 1

5. There is still a little difference here, mainly because the api actually needs to be centralized as a definition. The definition not only serves the service itself, but also needs to be provided to other callers.

6. The problem with Restful is that this can only be used as a suggestion, and this can be advanced gradually. But what should be optimized is the error handling part.

7. Good suggestion, you can modify our [template repo](https://github.com/tkeel-io/tkeel-template-go).
